name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 0 * * 0"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login into Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} --tag ${{secrets.DOCKER_USER}}/gitlab-runner
    - name: Build the Docker image
      run: docker build . --file Dockerfile
    - name: Publish Docker image to Docker Hub
      run: docker push ${{secrets.DOCKER_USER}}/gitlab-runner
